use_modular_headers!

require_relative '../node_modules/react-native/scripts/react_native_pods'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '15.5'

prepare_react_native_project!

target 'Chums' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  target 'ChumsTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # Enable ccache if required
      # :ccache_enabled => true
    )
  end
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper' => '0.74.0' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

# target 'Chums-tvOS' do
#   # Pods for Chums-tvOS

#   target 'Chums-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
# end
